# Name shown in GitHub Actions
name: Code scan and Lint

# This workflow can be called by another workflow
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

# Jobs
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v6

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # 3. Upgrade pip and Install dependencies
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          python -m pip install -r requirements.txt
          echo "Dependencies installed successfully"

      # 4. Code linting
      - name: Code linting
        run: |
          flake8 app.py
          flake8 tests/test_app.py

      # 5. Run tests
      - name: Run tests
        run: python -m pytest -v
