name: Dependency Review

# The dependency review action MUST run on pull requests to compare changes
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, synchronize, reopened]

permissions:
  contents: read # Required to read the repository's dependency graph

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Fetch the codebase
      - name: Checkout Repository
        uses: actions/checkout@v6

      # Step 2: Run the vulnerability check
      - name: Check Dependencies for Vulnerabilities
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
